# Default values for mw-kube-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mw:
  target: XXXXXXXXX
  apiKey: XXXXXXXXX
  configCheckInterval: "*/1 * * * *"
  apiUrlForConfigCheck: https://app.middleware.io
  dockerEndpoint: "unix:///var/run/docker.sock"
  selfProfiling: false
  profilingServerUrl: "https://profiling.middleware.io"
  agentFeatures:
    infraMonitoring: true
  apiKeyFromExistingSecret:
    enabled: false
    name: existing-secret
    key: existing-secret-key

clusterMetadata:
  name: "unknown"

replicaCount: 1

image:
  repository: ghcr.io/middleware-labs/mw-kube-agent
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.7.6

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: mw-service-account

namespace:
  name: mw-agent-ns
  
secret: 
  type: Opaque
  certSecretName: mw-app-certs
  csrfSecretName: mw-app-csrf
  keyHolderSecretName: mw-app-key-holder



role:
  name: mw-role

roleBinding:
  name: mw-role-binding

clusterRole:
  name: mw-cluster-role

clusterRoleBinding:
  name: mw-cluster-role-binding

service:
  name: mw-kube-agent-svc
  type: NodePort
  http:
    port: 9320
    targetPort: 9320
  grpc:
    port: 443 
    targetPort: 8443
  grpc2:
    port: 9319
    targetPort: 9319
  fluent:
    port: 8006
    targetPort: 8006
  
daemonset:
  name: mw-kube-agent
  configMap:
    name: mw-daemonset-otel-config
deployment:
  name: mw-kube-agent
  configMap:
    name: mw-deployment-otel-config

resources:
  requests:
    cpu: "100m"   # Default CPU request
    memory: "128Mi"  # Default memory request
  limits:
    cpu: "200m"   # Default CPU limit
    memory: "256Mi"  # Default memory limit

selectorLabels:
  k8s-app: mw-app
