{{- if .Values.features.enablePrometheusTargetAllocator }}
apiVersion: v1
kind: Service
metadata:
  name: mw-target-allocator
  namespace: {{ .Release.Namespace }}
  labels:
    app: mw-target-allocator
spec:
  selector:
    app: mw-target-allocator
  ports:
    - name: targetallocation
      protocol: TCP
      port: 80   
      targetPort: http  
  type: ClusterIP
{{- end }}