autoscaler:
  image:
    repository: ghcr.io/middleware-labs/odigos-autoscaler
    tag: middleware-test-0.0.15

scheduler:
  image:
    repository: ghcr.io/middleware-labs/vision-scheduler
    tag: middleware-test-0.0.1

langDetector:
  image:
    repository: ghcr.io/middleware-labs/vision-lang-detector
    tag: middleware-test-0.0.1

ui:
  image:
    repository: ghcr.io/middleware-labs/vision-ui
    tag: middleware-test-0.0.7

instrumentor:
  deleteLangDetectionPods: true
   # Ignored namespaces won't show up in vision-ui
  ignoredNamespaces:
    - mw-vision
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: ghcr.io/middleware-labs/odigos-instrumentor
    tag: middleware-test-0.0.1

visioncart:
  image:
    repository: ghcr.io/middleware-labs/vision-odiglet
    tag: middleware-test-0.0.1

telemetry:
  enabled: true
