autoscaler:
  image:
    repository: ghcr.io/middleware-labs/odigos-autoscaler
    tag: middleware-test-0.0.14

scheduler:
  image:
    repository: ghcr.io/middleware-labs/odigos-scheduler
    tag: middleware-test-0.0.1

langDetector:
  image:
    repository: ghcr.io/middleware-labs/odigos-lang-detector
    tag: middleware-test-0.0.1

ui:
  image:
    repository: ghcr.io/middleware-labs/odigos-ui
    tag: middleware-test-0.0.7

instrumentor:
  deleteLangDetectionPods: true
   # Ignored namespaces won't show up in odigos-ui
  ignoredNamespaces:
    - mw-vision
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: ghcr.io/middleware-labs/odigos-instrumentor
    tag: middleware-test-0.0.1

odiglet:
  image:
    repository: ghcr.io/middleware-labs/odigos-odiglet
    tag: middleware-test-0.0.1

telemetry:
  enabled: true
