autoscaler:
  image:
    repository: ghcr.io/middleware-labs/vision-autoscaler
    tag: middleware-test-0.0.22

scheduler:
  image:
    repository: ghcr.io/middleware-labs/vision-scheduler
    tag: middleware-test-0.0.5

langDetector:
  image:
    repository: ghcr.io/middleware-labs/vision-lang-detector
    tag: middleware-test-0.0.2

ui:
  image:
    repository: ghcr.io/middleware-labs/vision-ui
    tag: middleware-test-0.0.8

instrumentor:
  deleteLangDetectionPods: true
   # Ignored namespaces won't show up in vision-ui
  ignoredNamespaces:
    - mw-vision
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: ghcr.io/middleware-labs/vision-instrumentor
    tag: middleware-test-0.0.4

visioncart:
  image:
    repository: ghcr.io/middleware-labs/vision-odiglet
    tag: middleware-test-0.0.3

telemetry:
  enabled: true

dummy:
  enabled: true
