apiVersion: v2
name: mw-autoinstrumentation
description: Middleware Auto-instrumentation Helm Chart
version: 1.0.0
type: application
dependencies:
  - name: opentelemetry-operator
    version: "*"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-operator.enabled
    namespace: opentelemetry-operator-system 