
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: mw-autoinstrumentation
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  exporter:
    endpoint: http://mw-service.{{ .Release.Namespace }}:9319
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  python:
    env:
      - name: MW_AGENT_SERVICE
        value: mw-service.{{ .Release.Namespace }}.svc.cluster.local
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://mw-service.{{ .Release.Namespace }}:9320
  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://mw-service.{{ .Release.Namespace }}:9320
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://mw-service.{{ .Release.Namespace }}:9320
  java:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://mw-service.{{ .Release.Namespace }}:9319